In [1]:
%matplotlib inline

In [2]:
import os
import pathlib

In [3]:
import numpy as np
import pandas as pd

In [4]:
import xarray as xr

In [5]:
var_name = 'PRECIP'

In [6]:
dict_vars = {}
dict_vars['PRECIP'] = 'tprate'
dict_vars['SST'] = 'sst'
dict_vars['T2M'] = 't2m'
dict_vars['Z850'] = 'z'

In [7]:
dset = xr.open_dataset(f'/home/nicolasf/drives/auck_projects/END19101/Working/data/hindcasts/ecmwf/{var_name}/{var_name}_hindcasts_1993_2016_ecmwf_seasonal_anomalies.nc')

In [8]:
dsetm = dset.mean('number')

In [9]:
dsetm = dsetm.sortby('latitude')

In [10]:
dsetm = dsetm.sel(latitude=slice(None, 40))

In [11]:
one_month_lead = dsetm.sel(step=3).squeeze()

In [12]:
data_arr = one_month_lead[dict_vars[var_name]]

In [13]:
df = data_arr.to_dataframe()

In [14]:
df = df.loc[:,[dict_vars[var_name]]]

In [15]:
df_unstacked = df.unstack(level=['longitude','latitude'])

In [16]:
df_unstacked.shape

(288, 47160)

In [17]:
df_unstacked.head()

                  tprate                                            \
longitude          0.0           1.0           2.0           3.0
latitude           -90.0         -90.0         -90.0         -90.0
time
1993-01-01  1.106374e-10  1.106374e-10  1.106374e-10  1.106374e-10
1993-02-01 -1.691014e-10 -1.691014e-10 -1.691014e-10 -1.691014e-10
1993-03-01  1.099054e-10  1.099054e-10  1.099054e-10  1.099054e-10
1993-04-01 -1.352659e-10 -1.352659e-10 -1.352659e-10 -1.352659e-10
1993-05-01 -2.725533e-10 -2.725533e-10 -2.725533e-10 -2.725533e-10

                                                                    \
longitude          4.0           5.0           6.0           7.0
latitude           -90.0         -90.0         -90.0         -90.0
time
1993-01-01  1.106374e-10  1.106374e-10  1.106374e-10  1.106374e-10
1993-02-01 -1.691014e-10 -1.691014e-10 -1.691014e-10 -1.691014e-10
1993-03-01  1.099054e-10  1.099054e-10  1.099054e-10  1.099054e-10
1993-04-01 -1.352659e-10 -1.352659e-10 -1.352659e-10 -1.352659e-10
1993-05-01 -2.725533e-10 -2.725533e-10 -2.725533e-10 -2.725533e-10

                                        ...                              \
longitude          8.0           9.0    ...         350.0         351.0
latitude           -90.0         -90.0  ...          40.0          40.0
time                                    ...
1993-01-01  1.106374e-10  1.106374e-10  ...  4.432869e-09  5.726871e-09
1993-02-01 -1.691014e-10 -1.691014e-10  ...  2.851588e-09  1.501460e-09
1993-03-01  1.099054e-10  1.099054e-10  ... -6.686568e-10 -1.724915e-09
1993-04-01 -1.352659e-10 -1.352659e-10  ... -2.043552e-10 -4.365955e-10
1993-05-01 -2.725533e-10 -2.725533e-10  ...  3.075022e-10  3.084158e-10

                                                                    \
longitude          352.0         353.0         354.0         355.0
latitude            40.0          40.0          40.0          40.0
time
1993-01-01  8.271292e-09  4.504882e-09  4.592682e-09  2.691426e-09
1993-02-01 -9.221925e-10 -4.220254e-10 -3.525706e-10 -4.213644e-10
1993-03-01 -3.947704e-09 -3.421599e-09 -5.204524e-09 -4.625844e-09
1993-04-01 -4.277391e-10  1.955431e-11  2.446806e-10 -7.895411e-11
1993-05-01  3.359434e-10 -7.648241e-11 -2.765510e-10 -4.910949e-10


longitude          356.0         357.0         358.0         359.0
latitude            40.0          40.0          40.0          40.0
time
1993-01-01  1.059424e-09  2.001279e-09  2.988178e-09  1.296824e-09
1993-02-01 -4.086844e-10  5.524708e-11  1.324359e-11  5.953044e-10
1993-03-01 -3.114649e-09 -2.752286e-09 -2.476631e-09 -2.108655e-09
1993-04-01 -3.774378e-11 -3.372303e-10 -6.484350e-10  5.974211e-11
1993-05-01 -4.492620e-10 -6.177128e-10 -9.518207e-10 -4.948577e-10

[5 rows x 47160 columns]

In [18]:
time = df_unstacked.index

In [19]:
from dateutil.relativedelta import relativedelta

In [20]:
time = [x + relativedelta(months=3) for x in time]

In [21]:
df_unstacked.index = time

In [22]:
df_unstacked.head()

                  tprate                                            \
longitude          0.0           1.0           2.0           3.0
latitude           -90.0         -90.0         -90.0         -90.0
1993-04-01  1.106374e-10  1.106374e-10  1.106374e-10  1.106374e-10
1993-05-01 -1.691014e-10 -1.691014e-10 -1.691014e-10 -1.691014e-10
1993-06-01  1.099054e-10  1.099054e-10  1.099054e-10  1.099054e-10
1993-07-01 -1.352659e-10 -1.352659e-10 -1.352659e-10 -1.352659e-10
1993-08-01 -2.725533e-10 -2.725533e-10 -2.725533e-10 -2.725533e-10

                                                                    \
longitude          4.0           5.0           6.0           7.0
latitude           -90.0         -90.0         -90.0         -90.0
1993-04-01  1.106374e-10  1.106374e-10  1.106374e-10  1.106374e-10
1993-05-01 -1.691014e-10 -1.691014e-10 -1.691014e-10 -1.691014e-10
1993-06-01  1.099054e-10  1.099054e-10  1.099054e-10  1.099054e-10
1993-07-01 -1.352659e-10 -1.352659e-10 -1.352659e-10 -1.352659e-10
1993-08-01 -2.725533e-10 -2.725533e-10 -2.725533e-10 -2.725533e-10

                                        ...                              \
longitude          8.0           9.0    ...         350.0         351.0
latitude           -90.0         -90.0  ...          40.0          40.0
1993-04-01  1.106374e-10  1.106374e-10  ...  4.432869e-09  5.726871e-09
1993-05-01 -1.691014e-10 -1.691014e-10  ...  2.851588e-09  1.501460e-09
1993-06-01  1.099054e-10  1.099054e-10  ... -6.686568e-10 -1.724915e-09
1993-07-01 -1.352659e-10 -1.352659e-10  ... -2.043552e-10 -4.365955e-10
1993-08-01 -2.725533e-10 -2.725533e-10  ...  3.075022e-10  3.084158e-10

                                                                    \
longitude          352.0         353.0         354.0         355.0
latitude            40.0          40.0          40.0          40.0
1993-04-01  8.271292e-09  4.504882e-09  4.592682e-09  2.691426e-09
1993-05-01 -9.221925e-10 -4.220254e-10 -3.525706e-10 -4.213644e-10
1993-06-01 -3.947704e-09 -3.421599e-09 -5.204524e-09 -4.625844e-09
1993-07-01 -4.277391e-10  1.955431e-11  2.446806e-10 -7.895411e-11
1993-08-01  3.359434e-10 -7.648241e-11 -2.765510e-10 -4.910949e-10


longitude          356.0         357.0         358.0         359.0
latitude            40.0          40.0          40.0          40.0
1993-04-01  1.059424e-09  2.001279e-09  2.988178e-09  1.296824e-09
1993-05-01 -4.086844e-10  5.524708e-11  1.324359e-11  5.953044e-10
1993-06-01 -3.114649e-09 -2.752286e-09 -2.476631e-09 -2.108655e-09
1993-07-01 -3.774378e-11 -3.372303e-10 -6.484350e-10  5.974211e-11
1993-08-01 -4.492620e-10 -6.177128e-10 -9.518207e-10 -4.948577e-10

[5 rows x 47160 columns]

In [23]:
df_unstacked = df_unstacked.dropna(axis=1)

In [24]:
df_unstacked.tail()

                  tprate                                            \
longitude          0.0           1.0           2.0           3.0
latitude           -90.0         -90.0         -90.0         -90.0
2016-11-01  5.117351e-11  5.117351e-11  5.117351e-11  5.117351e-11
2016-12-01  6.243672e-11  6.243672e-11  6.243672e-11  6.243672e-11
2017-01-01 -2.401102e-11 -2.401102e-11 -2.401102e-11 -2.401102e-11
2017-02-01  1.941854e-11  1.941854e-11  1.941854e-11  1.941854e-11
2017-03-01  2.915258e-10  2.915258e-10  2.915258e-10  2.915258e-10

                                                                    \
longitude          4.0           5.0           6.0           7.0
latitude           -90.0         -90.0         -90.0         -90.0
2016-11-01  5.117351e-11  5.117351e-11  5.117351e-11  5.117351e-11
2016-12-01  6.243672e-11  6.243672e-11  6.243672e-11  6.243672e-11
2017-01-01 -2.401102e-11 -2.401102e-11 -2.401102e-11 -2.401102e-11
2017-02-01  1.941854e-11  1.941854e-11  1.941854e-11  1.941854e-11
2017-03-01  2.915258e-10  2.915258e-10  2.915258e-10  2.915258e-10

                                        ...                              \
longitude          8.0           9.0    ...         350.0         351.0
latitude           -90.0         -90.0  ...          40.0          40.0
2016-11-01  5.117351e-11  5.117351e-11  ... -1.250353e-09 -1.559259e-09
2016-12-01  6.243672e-11  6.243672e-11  ... -1.191587e-09 -2.328785e-09
2017-01-01 -2.401102e-11 -2.401102e-11  ... -9.714462e-11 -2.448748e-09
2017-02-01  1.941854e-11  1.941854e-11  ... -2.394186e-09 -1.729079e-09
2017-03-01  2.915258e-10  2.915258e-10  ... -3.580916e-09 -5.026034e-09

                                                                    \
longitude          352.0         353.0         354.0         355.0
latitude            40.0          40.0          40.0          40.0
2016-11-01 -4.300745e-10 -1.057153e-09 -5.906465e-10 -1.632620e-09
2016-12-01 -7.362342e-10 -8.568564e-10  7.297132e-12 -4.038303e-10
2017-01-01  1.994461e-09  3.104865e-09  5.886997e-09  5.021546e-09
2017-02-01  1.326758e-09  5.872255e-10  1.233504e-09  8.617439e-10
2017-03-01 -5.278126e-09 -3.063427e-09 -4.709622e-09 -3.270221e-09


longitude          356.0         357.0         358.0         359.0
latitude            40.0          40.0          40.0          40.0
2016-11-01 -9.731557e-10 -1.102397e-09 -1.029727e-09 -1.095384e-09
2016-12-01 -4.365039e-10  3.367330e-10  5.797617e-10 -2.736844e-10
2017-01-01  2.185366e-09  1.717946e-09  1.825375e-09  1.420364e-09
2017-02-01  5.340430e-10  7.603209e-10  3.249606e-10  1.972166e-11
2017-03-01 -9.723682e-10 -1.473006e-09 -1.473532e-09  7.100636e-10

[5 rows x 47160 columns]

In [25]:
df_unstacked.head()

                  tprate                                            \
longitude          0.0           1.0           2.0           3.0
latitude           -90.0         -90.0         -90.0         -90.0
1993-04-01  1.106374e-10  1.106374e-10  1.106374e-10  1.106374e-10
1993-05-01 -1.691014e-10 -1.691014e-10 -1.691014e-10 -1.691014e-10
1993-06-01  1.099054e-10  1.099054e-10  1.099054e-10  1.099054e-10
1993-07-01 -1.352659e-10 -1.352659e-10 -1.352659e-10 -1.352659e-10
1993-08-01 -2.725533e-10 -2.725533e-10 -2.725533e-10 -2.725533e-10

                                                                    \
longitude          4.0           5.0           6.0           7.0
latitude           -90.0         -90.0         -90.0         -90.0
1993-04-01  1.106374e-10  1.106374e-10  1.106374e-10  1.106374e-10
1993-05-01 -1.691014e-10 -1.691014e-10 -1.691014e-10 -1.691014e-10
1993-06-01  1.099054e-10  1.099054e-10  1.099054e-10  1.099054e-10
1993-07-01 -1.352659e-10 -1.352659e-10 -1.352659e-10 -1.352659e-10
1993-08-01 -2.725533e-10 -2.725533e-10 -2.725533e-10 -2.725533e-10

                                        ...                              \
longitude          8.0           9.0    ...         350.0         351.0
latitude           -90.0         -90.0  ...          40.0          40.0
1993-04-01  1.106374e-10  1.106374e-10  ...  4.432869e-09  5.726871e-09
1993-05-01 -1.691014e-10 -1.691014e-10  ...  2.851588e-09  1.501460e-09
1993-06-01  1.099054e-10  1.099054e-10  ... -6.686568e-10 -1.724915e-09
1993-07-01 -1.352659e-10 -1.352659e-10  ... -2.043552e-10 -4.365955e-10
1993-08-01 -2.725533e-10 -2.725533e-10  ...  3.075022e-10  3.084158e-10

                                                                    \
longitude          352.0         353.0         354.0         355.0
latitude            40.0          40.0          40.0          40.0
1993-04-01  8.271292e-09  4.504882e-09  4.592682e-09  2.691426e-09
1993-05-01 -9.221925e-10 -4.220254e-10 -3.525706e-10 -4.213644e-10
1993-06-01 -3.947704e-09 -3.421599e-09 -5.204524e-09 -4.625844e-09
1993-07-01 -4.277391e-10  1.955431e-11  2.446806e-10 -7.895411e-11
1993-08-01  3.359434e-10 -7.648241e-11 -2.765510e-10 -4.910949e-10


longitude          356.0         357.0         358.0         359.0
latitude            40.0          40.0          40.0          40.0
1993-04-01  1.059424e-09  2.001279e-09  2.988178e-09  1.296824e-09
1993-05-01 -4.086844e-10  5.524708e-11  1.324359e-11  5.953044e-10
1993-06-01 -3.114649e-09 -2.752286e-09 -2.476631e-09 -2.108655e-09
1993-07-01 -3.774378e-11 -3.372303e-10 -6.484350e-10  5.974211e-11
1993-08-01 -4.492620e-10 -6.177128e-10 -9.518207e-10 -4.948577e-10

[5 rows x 47160 columns]

In [26]:
df_unstacked.to_csv(f'/home/nicolasf/drives/auck_projects/END19101/Working/outputs/ECMWF_CSVs/{var_name}_1993_2016_ecmwf.csv')

In [27]:
df_unstacked.tail()

                  tprate                                            \
longitude          0.0           1.0           2.0           3.0
latitude           -90.0         -90.0         -90.0         -90.0
2016-11-01  5.117351e-11  5.117351e-11  5.117351e-11  5.117351e-11
2016-12-01  6.243672e-11  6.243672e-11  6.243672e-11  6.243672e-11
2017-01-01 -2.401102e-11 -2.401102e-11 -2.401102e-11 -2.401102e-11
2017-02-01  1.941854e-11  1.941854e-11  1.941854e-11  1.941854e-11
2017-03-01  2.915258e-10  2.915258e-10  2.915258e-10  2.915258e-10

                                                                    \
longitude          4.0           5.0           6.0           7.0
latitude           -90.0         -90.0         -90.0         -90.0
2016-11-01  5.117351e-11  5.117351e-11  5.117351e-11  5.117351e-11
2016-12-01  6.243672e-11  6.243672e-11  6.243672e-11  6.243672e-11
2017-01-01 -2.401102e-11 -2.401102e-11 -2.401102e-11 -2.401102e-11
2017-02-01  1.941854e-11  1.941854e-11  1.941854e-11  1.941854e-11
2017-03-01  2.915258e-10  2.915258e-10  2.915258e-10  2.915258e-10

                                        ...                              \
longitude          8.0           9.0    ...         350.0         351.0
latitude           -90.0         -90.0  ...          40.0          40.0
2016-11-01  5.117351e-11  5.117351e-11  ... -1.250353e-09 -1.559259e-09
2016-12-01  6.243672e-11  6.243672e-11  ... -1.191587e-09 -2.328785e-09
2017-01-01 -2.401102e-11 -2.401102e-11  ... -9.714462e-11 -2.448748e-09
2017-02-01  1.941854e-11  1.941854e-11  ... -2.394186e-09 -1.729079e-09
2017-03-01  2.915258e-10  2.915258e-10  ... -3.580916e-09 -5.026034e-09

                                                                    \
longitude          352.0         353.0         354.0         355.0
latitude            40.0          40.0          40.0          40.0
2016-11-01 -4.300745e-10 -1.057153e-09 -5.906465e-10 -1.632620e-09
2016-12-01 -7.362342e-10 -8.568564e-10  7.297132e-12 -4.038303e-10
2017-01-01  1.994461e-09  3.104865e-09  5.886997e-09  5.021546e-09
2017-02-01  1.326758e-09  5.872255e-10  1.233504e-09  8.617439e-10
2017-03-01 -5.278126e-09 -3.063427e-09 -4.709622e-09 -3.270221e-09


longitude          356.0         357.0         358.0         359.0
latitude            40.0          40.0          40.0          40.0
2016-11-01 -9.731557e-10 -1.102397e-09 -1.029727e-09 -1.095384e-09
2016-12-01 -4.365039e-10  3.367330e-10  5.797617e-10 -2.736844e-10
2017-01-01  2.185366e-09  1.717946e-09  1.825375e-09  1.420364e-09
2017-02-01  5.340430e-10  7.603209e-10  3.249606e-10  1.972166e-11
2017-03-01 -9.723682e-10 -1.473006e-09 -1.473532e-09  7.100636e-10

[5 rows x 47160 columns]

In [28]:
df_unstacked.shape

(288, 47160)